#!/bin/bash
file=email_change.csv
APIkey=

header=true
while read line || [ -n "$line" ]
do
if [ "$header" = 'true' ];
then
header=false
continue
fi

account_id=`echo $line | cut -d ',' -f1`
old_email=`echo $line | cut -d ',' -f2`
email=`echo $line | cut -d ',' -f3`

echo "$account_id"':' ' old_email:'"$old_email" ' -> new_email:'"$email"

email="${email%%[[:cntrl:]]}"

curl --request PUT \
--url "https://api.atlassian.com/users/${account_id}/manage/email" \
--header "Authorization: Bearer ${APIkey}" \
--header 'Content-Type: application/json' \
--data '{
  "email": "'"$email"'"
}'

done <$file

# #########################################
# To-do list :

# The API key can be generated by following “

# Manage an organization with the admin APIs“ article.

# CSV file mentioned in the script can need to be in below mentioned format. Here is a sample CSV file

# account_id,old_email,email,
# 1234,old_email1@domain.com,new_email1@domain.com,
# 4532,old_email2@domain.com,new_email2@domain.com,
# 2000,old_email3@domain.com,new_email3@domain.com,
# You can get the account ID by exporting the CSV file under the managed account.

# Reference doc: Export managed accounts

########################################